# Generated by Django 3.0.2 on 2020-01-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20200119_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='departureTime',
            new_name='time',
        ),
    ]
