# Generated by Django 3.0.2 on 2020-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20200119_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pickupDirections',
            field=models.CharField(default='', max_length=200),
        ),
    ]
